use_frameworks!

platform :ios, '12.0'

target 'Search_Example' do
  pod 'Search', :path => '../'

  target 'Search_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
